// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class Address
    {
        public int addressID { get; set; }
        public string addressLine { get; set; }
        public string suburb { get; set; }
        public int postcode { get; set; }
        public string region { get; set; }
        public string country { get; set; }
    }
}