// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class Category
    {
        public int categoryID { get; set; }
        public int? parentCategoryID { get; set; }
        public string categoryName { get; set; }
    }
}