// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class CustomerOrder
    {
        public int orderID { get; set; }
        public int customerID { get; set; }
        public DateTime orderDate { get; set; }
        public DateTime? datePaid { get; set; }
    }
}