// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class ProductInOrder
    {
        public int orderID { get; set; }
        public int productID { get; set; }
        public int numberOf { get; set; }
        public decimal? totalItemCost { get; set; }
    }
}