// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class Product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public decimal productCost { get; set; }
        public string productDescription { get; set; }
        public string productImage { get; set; }
        public int categoryID { get; set; }

        public Category category { get; set; }  
    }
}