// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCEcommerce.Models
{
    public partial class Review
    {
        public int reviewID { get; set; }
        public int customerID { get; set; }
        public DateOnly reviewDate { get; set; }
        public int productID { get; set; }
        public int rating { get; set; }
        public string reviewDescription { get; set; }
    }
}